### ISSUE TITLE
Vireo-172 dataset

### ISSUE THREAD

**Issue by lzl2040** [Jianing-Qiu/PARNet#1]
How to download this dataset?

**Comment by Jianing-Qiu** [comment]
Hi there, you need to contact the authors of Vireo-172 in order to download their dataset
"Deep-based ingredient recognition for cooking recipe retrieval"

**Comment by lzl2040** [comment]
> Hi there, you need to contact the authors of Vireo-172 in order to download their dataset "Deep-based ingredient recognition for cooking recipe retrieval"

Thanks for your reply! But I found that the email provided in the paper is wrong so I can't contact the authors by email. Could you please provide me a correct email? I would really appreciate it.

**Comment by Jianing-Qiu** [comment]
ohhh, in that case, you can search the latest articles of the authors, and find their up-to-date contact info there!

**Comment by lzl2040** [comment]
> ohhh, in that case, you can search the latest articles of the authors, and find their up-to-date contact info there!

OK! Thank you!
